Repository DaengPlace/FrontEnd, pull requests merged in 2024-11, with the labels that each got.

#6 [Feat] NavBottom 컴포넌트 제작
  .storybook/preview.js
  package.json
  src/app/ClientLayout.js
  src/app/globals.css
  src/app/layout.js
  src/app/place/page.jsx
  src/app/recommend/page.jsx
  src/app/search/page.jsx
  src/app/user/page.jsx
  src/components/.gitkeep
  src/components/common/NavBottom/NavBottom.jsx
  src/components/common/NavBottom/NavBottom.stories.js
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/.gitkeep
  src/styles/theme.js
  yarn.lock
Labels: feat, fix

#9 [Feat] 공통 컴포넌트 제작
  public/assets/common/check_small.svg
  public/assets/common/dog.svg
  public/assets/common/no_check_small.svg
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/BottomSheet/BottomSheet.stories.js
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.stories.js
  src/components/common/Checkbox/Checkbox.jsx
  src/components/common/Checkbox/Checkbox.stories.js
  src/components/common/Input/Input.jsx
  src/components/common/Input/Input.stories.js
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/Modal.stories.js
  src/components/common/NavBottom/NavBottom.stories.js
Labels: design, feat

#12 [Feat] 유효성 검사 react-hook-form 사용
  package.json
  src/components/common/Input/Input.jsx
  yarn.lock
Labels: feat

#27 [Design] Header story 생성 완료
  public/assets/mainpage/Logo.png
  src/app/ClientLayout.js
  src/app/main/page.jsx
  src/app/mypage/page.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.stories.js
Labels: design

#29 [Design] 즐겨찾기 목록 페이지 퍼블리싱
  next.config.mjs
  public/assets/mypage/facilityImage.png
  src/app/ClientLayout.js
  src/app/mypage/bookmark/map/page.jsx
  src/app/mypage/bookmark/page.jsx
  src/app/mypage/page.jsx
  src/components/bookmark/BigFacilityCard/BigFacilityCard.jsx
  src/components/bookmark/ButtonsContainer/ButtonsContainer.jsx
  src/components/bookmark/ScrollableContainer/ScrollableContainer.jsx
  src/components/mypage/Activities/Activities.jsx
  src/data/facilities.js
Labels: design

#34 [Design] 리뷰 관련 페이지 작업 (수정)
  public/assets/image (1).png
  src/app/place/page.jsx
  src/app/place/placedetail/page.jsx
  src/app/place/placemap/page.jsx
  src/app/place/placesearch/page.jsx
  src/app/placedetail/page.jsx
  src/app/reviews/PhotoReview/page.jsx
  src/app/reviews/ReviewDetail/page.jsx
  src/app/reviews/page.jsx
  src/app/reviews/reviewScan/page.jsx
  src/app/reviews/reviewsInput/page.jsx
  src/components/bookmark/BigFacilityCard/BigFacilityCard.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.stories.js
  src/components/main/Menu/Menu.jsx
  src/components/place/Hr2/Hr2.jsx
  src/components/place/placedetail/ImageContainer/ImageContainer.jsx
  src/components/place/placedetail/MapBottomSheet/MapBottomSheet.jsx
  src/components/place/placedetail/PlaceInfo/PlaceInfo.jsx
  src/components/place/placedetail/ReviewSection/ReviewSection.jsx
  src/components/place/placedetail/WriteReviewButton/WriteReviewButton.jsx
  src/components/place/placemap/BottomSheet/BottomSheet.jsx
  src/components/place/placemap/FilterButtons/FilterButtons.jsx
  src/components/place/placemap/FloatingButton/FloatingButton.jsx
  src/components/place/placemap/Map/Map.jsx
  src/components/place/placemap/SearchBar/SearchBar.jsx
  src/components/place/placemap/Tabs/Tabs.jsx
  src/components/place/placesearch/BottomSheet/BottomSheet.jsx
  src/components/place/placesearch/Card/Card.jsx
  src/components/place/placesearch/CardList/CardList.jsx
  src/components/place/placesearch/FilterButtons/FilterButtons.jsx
  src/components/place/placesearch/SearchBar/SearchBar.jsx
  src/components/place/placesearch/Tabs/Tabs.jsx
  src/components/reviews/PageHeader/PageHeader.jsx
  src/components/reviews/PhotoReviewContainer/PhotoReviewContainer.jsx
  src/components/reviews/ReviewList/ReviewList.jsx
  src/components/reviews/ReviewSummary/ReviewSummary.jsx
  src/components/reviews/TagSection/TagSection.jsx
  src/components/reviews/reviewsInput/AddMediaSection/AddMediaSection.jsx
  src/components/reviews/reviewsInput/CategorySection/CategorySection.jsx
  src/components/reviews/reviewsInput/ProfileSection/ProfileSection.jsx
  src/components/reviews/reviewsInput/RatingSection/RatingSection.jsx
  src/components/reviews/reviewsInput/ReviewTextSection/ReviewTextSection.jsx
  src/components/reviews/reviewsInput/ScrollToTopButton/ScrollToTopButton.jsx
  src/components/reviews/reviewsInput/SubmitButton/SubmitButton.jsx
  src/components/reviews/reviewsInput/TagSection/TagSection.jsx
Labels: design
