Repository DaengPlace/FrontEnd, pull requests merged in 2024-12, with the labels that each got.

#38 [Design] 성향별 시설 추천 페이지 퍼블리싱
  src/app/ClientLayout.js
  src/app/main/page.jsx
  src/app/mypage/bookmark/map/page.jsx
  src/app/mypage/bookmark/page.jsx
  src/app/mypage/myreviews/page.jsx
  src/app/mypage/page.jsx
  src/app/place/page.jsx
  src/app/recommend/dogtest/page.jsx
  src/app/recommend/page.jsx
  src/app/recommend/test/page.jsx
  src/app/recommend/testresult/page.jsx
  src/app/recommend/usertest/page.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/Header/Header.jsx
  src/components/main/Banner/Banner.jsx
  src/components/main/FacilitiesSection/FacilitiesSection.jsx
  src/components/main/FacilityCard/FacilityCard.jsx
  src/components/mypage/AccountManagement/AccountManagement.jsx
  src/components/mypage/Activities/Activities.jsx
  src/components/mypage/PetProfile/PetProfile.jsx
  src/components/mypage/SectionHeader/SectionHeader.jsx
  src/components/mypage/UserProfile/UserProfile.jsx
  src/components/mypage/bookmark/BigFacilityCard/BigFacilityCard.jsx
  src/components/mypage/bookmark/ButtonsContainer/ButtonsContainer.jsx
  src/components/mypage/bookmark/ScrollableContainer/ScrollableContainer.jsx
  src/components/mypage/myreviews/ReviewCard/ReviewCard.jsx
  src/components/place/placemap/Map/Map.jsx
  src/components/recommend/DogCard/DogCard.jsx
  src/components/recommend/DogInfo/DogInfo.jsx
  src/components/recommend/DogPersonality/DogPersonality.jsx
  src/components/recommend/DogTags/DogTags.jsx
  src/components/recommend/FeatureGroup/FeatureGroup.jsx
  src/components/recommend/FeatureTitle/FeatureTitle.jsx
  src/components/reviews/ReviewList/ReviewList.jsx
  src/data/DogsTest.js
  src/data/cardsData.js
Labels: design

#41 [Fix] 인증번호 재발송, 인증확인 버튼
  src/app/signin/page.jsx
  src/components/common/Button/Button.jsx
Labels: fix

#45 [Fix] Deploy 오류 해결
  src/app/mypage/profile/page.jsx
  src/app/signin/info/page.jsx
Labels: fix

#49 Chore(#44): eslint.json 파일 수정
  .eslintrc.json
Labels: chore

#53 [Fix] Deploy 오류 해결
  .eslintrc.json
  package.json
  src/app/mypage/profile/page.jsx
  src/app/signin/info/page.jsx
  yarn.lock
Labels: fix

#56 [Fix] Deploy 오류 해결 - useSearchParams() Suspense 처리
  src/app/place/placedetail/page.jsx
  src/app/place/placemap/page.jsx
  src/app/place/placesearch/page.jsx
Labels: fix

#57 [Fix] Deploy 오류 해결
  next.config.mjs
  src/app/globals.css
  src/app/layout.js
  src/app/place/placedetail/page.jsx
Labels: fix

#58 Fix(#44): 메타데이터 변경
  src/app/layout.js
Labels: fix

#59 Chore(#44): gitignore 파일에 babel 관련 파일 추가
  .gitignore
Labels: chore

#71 [Feat] axiosInstance 생성
  src/apis/.gitkeep
  src/apis/axiosInstance
Labels: feat

#74 [Design] 로그인 필요 서비스 바텀시트 구현
  public/assets/mainpage/bookmarkIcon.png
  public/assets/mainpage/bookmarkIcon.svg
  public/assets/mainpage/daengplaceIcon.png
  public/assets/mainpage/daengplaceIcon.svg
  public/assets/mainpage/recommendIcon.png
  public/assets/mainpage/recommendIcon.svg
  src/app/layout.js
  src/app/page.js
  src/app/place/placedetail/page.jsx
  src/app/recommend/page.jsx
  src/components/common/AuthGuard/AuthGuard.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/common/Header/Header.jsx
  src/components/common/NavBottom/NavBottom.jsx
  src/components/main/Menu/Menu.jsx
  src/components/place/placedetail/PlaceInfo/PlaceInfo.jsx
  src/components/place/placesearch/Card/Card.jsx
  src/contexts/AuthContext.jsx
Labels: design, feat

#80 [Design] 전체 스타일링 수정
  src/app/layout.js
  src/components/signin/Header/Header.jsx
Labels: design

#81 [Design] 스타일링 수정
  src/app/place/placesearch/page.jsx
  src/contexts/AuthContext.jsx
Labels: design

#82 Design(#39): mypage/myreviews 수정삭제 버튼 활성화
  src/components/mypage/myreviews/ReviewCard/ReviewCard.jsx
  src/contexts/AuthContext.jsx
Labels: design

#87 [Design] 접속화면 svg 변경
  public/assets/common/start.svg
Labels: design

#89 [Feat] 회원가입 완료, 이메일 인증 완료
  src/apis/auth/email/postCheckCode.jsx
  src/apis/auth/email/postCheckDuplicate.jsx
  src/apis/auth/email/postSendCode.jsx
  src/apis/auth/postSignin.jsx
  src/apis/dog/deletePet.jsx
  src/apis/dog/getBreedTypes.jsx
  src/apis/dog/getPetDetail.jsx
  src/apis/dog/postPetUpdate.jsx
  src/apis/dog/postRegister.jsx
  src/app/auth/google/page.jsx
  src/app/dog/confirm/page.jsx
  src/app/dog/edit/page.jsx
  src/app/dog/info/page.jsx
  src/app/page.js
  src/app/signin/info/page.jsx
  src/app/signin/page.jsx
  src/app/signin/profile/page.jsx
  src/components/common/BottomSheet/BottomSheet.jsx
  src/components/dog/DogBottomSheet/DogBottomSheet.jsx
  src/components/dog/DogInfo/DogInfo.jsx
  src/data/dogData.js
  src/hooks/auth/usePostSignin.js
  src/hooks/dog/useGetBreedTypes.js
  src/stores/dogStore.js
Labels: feat

#91 [Feat] 마이페이지 API 연동
  src/apis/dog/putPetUpdate.jsx
  src/apis/favorite/getBookmarks.jsx
  src/apis/places/getPlacesByPlaceId.jsx
  src/apis/reviews/getReviews.jsx
  src/apis/user/getUserProfile.jsx
  src/apis/user/putUserUpdate.jsx
  src/app/ClientLayout.js
  src/app/dog/edit/page.jsx
  src/app/dog/info/page.jsx
  src/app/mypage/bookmark/page.jsx
  src/app/mypage/editpet/page.jsx
  src/app/mypage/myreviews/page.jsx
  src/app/mypage/page.jsx
  src/app/mypage/profile/page.jsx
  src/components/mypage/AccountManagement/AccountManagement.jsx
  src/components/mypage/PetProfile/PetProfile.jsx
  src/components/mypage/myreviews/ReviewCard/ReviewCard.jsx
  src/contexts/AuthContext.jsx
Labels: feat

#98 [Feat] 메인페이지 API 연동
  src/apis/place/getPopularFacilities.jsx
  src/app/main/page.jsx
  src/components/main/FacilitiesSection/FacilitiesSection.jsx
  src/components/main/FacilityCard/FacilityCard.jsx
Labels: feat

#99 [Feat] 성향별 추천 페이지 API 연동
  src/apis/places/getPlacesByPlaceId.jsx
  src/apis/places/getRecommend.jsx
  src/apis/traits/getTraits.jsx
  src/apis/traits/postTraits.jsx
  src/app/main/page.jsx
  src/app/recommend/dogtest/page.jsx
  src/app/recommend/page.jsx
  src/app/recommend/testresult/page.jsx
  src/app/recommend/usertest/page.jsx
  src/components/recommend/DogInfo/DogInfo.jsx
  src/stores/traitStore.js
Labels: feat

#114 [Refactor] 스타일링 2차 수정
  src/app/place/page.jsx
  src/app/place/placedetail/page.jsx
  src/app/place/placesearch/page.jsx
  src/app/reviews/receiptCapture/page.jsx
  src/app/reviews/reviewScan/page.jsx
  src/components/common/Header/Header.jsx
  src/components/common/ScrollToTopButton/ScrollToTopButton.jsx
  src/components/common/SelectBox/SelectBox.jsx
  src/components/mypage/AccountManagement/AccountManagement.jsx
  src/components/place/ReviewList/ReviewList.jsx
  src/components/place/placedetail/ImageContainer/ImageContainer.jsx
  src/components/place/placedetail/PlaceInfo/PlaceInfo.jsx
  src/components/place/placedetail/ReviewSection/ReviewSection.jsx
  src/components/place/placedetail/WriteReviewButton/WriteReviewButton.jsx
  src/components/place/placemap/FilterButtons/FilterButtons.jsx
  src/components/place/placesearch/BottomSheet/BottomSheet.jsx
  src/components/place/placesearch/Card/Card.jsx
  src/components/place/placesearch/CardList/CardList.jsx
  src/components/place/placesearch/FilterButtons/FilterButtons.jsx
  src/components/place/placesearch/SearchBar/SearchBar.jsx
Labels: design, feat

#119 [Refactor] 3차 수정
  src/app/dog/edit/page.jsx
  src/app/main/page.jsx
  src/app/mypage/bookmark/page.jsx
  src/app/mypage/editpet/page.jsx
  src/app/mypage/myreviews/page.jsx
  src/app/mypage/registerpet/confirm/page.jsx
  src/app/place/page.jsx
  src/app/place/placedetail/page.jsx
  src/app/place/placemap/page.jsx
  src/app/place/placesearch/page.jsx
  src/app/recommend/dogtest/page.jsx
  src/app/recommend/page.jsx
  src/app/recommend/usertest/page.jsx
  src/app/reviews/PhotoReview/page.jsx
  src/app/reviews/ReviewDetail/page.jsx
  src/app/reviews/page.jsx
  src/app/reviews/receiptCapture/page.jsx
  src/app/reviews/reviewScan/page.jsx
  src/app/reviews/reviewsInput/page.jsx
  src/app/signin/page.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Divider/Divider.jsx
  src/components/common/Form/Form.jsx
  src/components/dog/DogInfo/DogInfo.jsx
  src/components/main/FacilitiesSection/FacilitiesSection.jsx
  src/components/main/FacilityCard/FacilityCard.jsx
  src/components/place/Hr2/Hr2.jsx
  src/components/place/placedetail/WriteReviewButton/WriteReviewButton.jsx
  src/components/place/placemap/BottomSheet/BottomSheet.jsx
  src/components/place/placemap/Map/Map.jsx
  src/components/place/placemap/SearchBar/SearchBar.jsx
  src/components/place/placesearch/BottomSheet/BottomSheet.jsx
  src/components/place/placesearch/Card/Card.jsx
  src/components/place/placesearch/SearchBar/SearchBar.jsx
  src/components/reviews/PageHeader/PageHeader.jsx
  src/components/reviews/PhotoReview/SubHeader/SubHeader.jsx
  src/components/reviews/PhotoReviewContainer/PhotoReviewContainer.jsx
  src/components/reviews/ReviewList/ReviewList.jsx
  src/components/reviews/ReviewSummary/ReviewSummary.jsx
  src/components/reviews/ReviewsDetail/ReviewCard/ReviewCard.jsx
  src/components/reviews/ReviewsDetail/SubHeader/SubHeader.jsx
  src/components/reviews/TagSection/TagSection.jsx
  src/components/reviews/reviewsInput/AddMediaSection/AddMediaSection.jsx
  src/components/reviews/reviewsInput/CategorySection/CategorySection.jsx
  src/components/reviews/reviewsInput/RatingSection/RatingSection.jsx
  src/components/reviews/reviewsInput/ReviewTextSection/ReviewTextSection.jsx
  src/components/reviews/reviewsInput/TagSection/TagSection.jsx
Labels: design, feat

#120 [Refactor] 4차 수정
  src/app/ClientLayout.js
  src/app/dog/edit/page.jsx
  src/app/dog/info/page.jsx
  src/app/mypage/page.jsx
  src/app/recommend/page.jsx
  src/app/reviews/PhotoReview/page.jsx
  src/components/common/ConfirmModal/ConfirmModal.jsx
  src/components/place/ReviewList/ReviewList.jsx
  src/components/reviews/ReviewsDetail/ReviewCard/ReviewCard.jsx
  src/hooks/auth/usePostSignin.js
Labels: design, feat

#122 [Refactor] 5차 수정
  public/assets/kakaotalk.png
  src/app/mypage/registerpet/confirm/page.jsx
  src/components/common/Footer/Footer.jsx
Labels: design, feat
